### ISSUE TITLE
Error "too many arguments provided to function-like macro invocation" using QMap

### ISSUE THREAD

**Issue by ulmino** [Skycoder42/QJsonSerializer#10]
I get this error
"too many arguments provided to function-like macro invocation"

using QMap as Property:
 Q_PROPERTY( QMap<QString, myClass*> mylist MEMBER mylist )

I did a lot of investigating in the net and the result is, that Q_PROPERTY is a macro of Q_OBJECT, which doesn't support variadic templates, so the comma necessary to define the QMap within Q_PROPERTY macro is not supported.

The only way to remove the error is to bundle the QMap definition in a Typedef, but seems to be not supported in QJsonSerializer library.

In the examples there is no example for using QMap; maybe I used it wrong.

Could you add a example how to use QMap with custom class to serialize and deserialize?

**Comment by Skycoder42** [comment]
I am not shure where your problem comes from, but generally, maps do work, as `Q_PROPERTY` actually *is* a variadic macro on compilers that support it (See [qobjectdefs.h:109](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qobjectdefs.h#n109)).

In [testgadget.h:67](https://github.com/Skycoder42/QtJsonSerializer/blob/master/tests/auto/jsonserializer/GadgetSerializerTest/testgadget.h#L67) you can see me using maps - and that compiles completely fine, as you can see in all the CI-builds. So at least on the support platforms, it should work.

Which platform are you on, what compiler and compiler version are you using and which version of Qt are you trying to use the library with? That will help narrow down from where the error comes.

**Comment by ulmino** [comment]
Hi,

you are right it compiles fine, but the intellisense of Qt creator keeps showing the errors.

The target platforms are Windows, iOS and Android

I’m testing actually on Windows using Qt 5.11.1 and mingw 5.3.0.

Maybe it is just a setting in Qt creator to avoid the errors in intellisense?

Mit freundlichen Grüßen
Ulm Stefan

**Comment by Skycoder42** [comment]
I guess thats the reason. You can try switching the code model you are currently using.Either the internal codemodel is not able to detect this correctly, or the clang is not able to detect the compiler-features of mingw correctly - I can't say which one it is.

Simply check which one is active, the internal or the clang code model and the enable or disable the clang codemodel plugin based on that.

Also: I would like to keep this issue open because of the second part of it:
> Could you add a example how to use QMap with custom class to serialize and deserialize?

I will close this issue once I got the chance to do that.

Und schönen Gruß zurück!

**Comment by Skycoder42** [comment]
As a sidenote: I am also experiencing this in Qt Creator now. aparrently clang detects the macro definition wrong.

A simle workaround is to add a ifdef around the statement the disables it unless moc is run:

```
#ifdef Q_MOC_RUN //workaround for clang code model
	Q_PROPERTY(QMap<QString, int> property MEMBER property);
#endif
```

**Comment by Skycoder42** [comment]
I have now added support for typedefs to the library. See https://github.com/Skycoder42/QtJsonSerializer#support-for-using-and-typedef.

You can already get it from the master branch or wait for the next release which is due in a few days
