### ISSUE TITLE
Using QtJsonSerializer as a static library 

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#12]
Hello! I have a static version of Qt 5.12 (Windows).  QtJsonSerializer was installed as a static lib. But the problem is linked with Q_JSONSERIALIZER_EXPORT define. It is redundant for static version. How this can be fixed? I prefer CMake (Qt developers even dropped qbs, qmake will be obsolete too in the far future, the will concentrate on CMake). BTW, I use QtJsonSerializer CMake module.

**Comment by arietto** [comment]
As a workaround, I use the following call
qmake.exe DEFINES+="STATIC_QJSON_SERIALIZER"

I have the following local modification in qtjsonserializer_global.h


#if defined(STATIC_QJSON_SERIALIZER)
    #define Q_JSONSERIALIZER_EXPORT
#else
    #if defined(QT_BUILD_JSONSERIALIZER_LIB)
        #define Q_JSONSERIALIZER_EXPORT Q_DECL_EXPORT
    #else
        #define Q_JSONSERIALIZER_EXPORT Q_DECL_IMPORT
    #endif
#endif

Each static library consumer must define STATIC_QJSON_SERIALIZER.

**Comment by Skycoder42** [comment]
I am aware of the planned changes in build systems of the Qt Company. I am still using qmake as all official Qt modules are currenlty built with qmake as well. I need some of their internal tools to create "true" Qt modules. I will of course switch my projects to cmake once Qt officially performs this step as well.

Regarding the static part: I always though Qt would automatically define the `Q_DECL_EXPORT` and `Q_DECL_IMPOR` macros to be empty for static builds. After checking how qtbase handles this, I realised that was a false assumption. Taken from QtNetwork, the library export macros are defined as:

```
#ifndef QT_STATIC
#  if defined(QT_BUILD_NETWORK_LIB)
#    define Q_NETWORK_EXPORT Q_DECL_EXPORT
#  else
#    define Q_NETWORK_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define Q_NETWORK_EXPORT
#endif
```

You can use the same as workround with `Q_JSONSERIALIZER_EXPORT` until I find the time to update the code base. This way you should be able to use the library statically without defining that extra macro in any consumer. I will keep the issue open until this was fixed in the code.
