### ISSUE TITLE
Serialize QSet<MyEnum> as QSet<int>

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#19]
Hello! I'd like to serialize `Q_GADGET` member `QSet<MyEnum> enumSet` as a set of `int`'s. But serialization converts it to string, though I didn't called setEnumAsString(true).

**Comment by Skycoder42** [comment]
I am afraid that is a limitation of enums... Because it is not possible to get a `QMetaEnum` from a `QMetaType` alone, we can only serialize enums correctly if they are stored as properties. (See [qjsonserializer.cpp#L261](https://github.com/Skycoder42/QtJsonSerializer/blob/master/src/jsonserializer/qjsonserializer.cpp#L261)).

So as long as Qt does not add a method to get the `QMetaEnum` from the type id, I cannot do anything to solve this problem.

A possible workaround for your case would be to register a special custom converter with a high priority that takes care of this special case. If you need help with that, I can provide you a skeleton for the implementation.

**Comment by Skycoder42** [comment]
Update: I just checked the documentation and there might be a way around this issue... I will try it out within the next few days and maybe we can solve the problem.

**Comment by Skycoder42** [comment]
Fixed in master, will be available with the 4.0.0 release.
