### ISSUE TITLE
What to do to reduce compile time and binary size used for registering unneeded type converters

### ISSUE THREAD

**Issue by useful-friend** [Skycoder42/QJsonSerializer#24]
Hello there.
I'm currently using version 3.3.1-3 and I have to keep using that version because I have to use Qt 5.12.4.
The problem as mentioned in the title is that I need to compact my final binary file and also reduce compile time but registering all the converters is taking a lot of resources.
Can you show me a clean way to remove those converters and register only needed ones?

Thanks in advance.

**Comment by Skycoder42** [comment]
The easiest way would be to simply remove all unneeded types from the [src/jsonserializer/typesplit.pri](https://github.com/Skycoder42/QtJsonSerializer/blob/3.3.1-3/src/jsonserializer/typesplit.pri) file.

You could even remove almost everything from the file if you don't want anything registered at all. However, the generation of the primary hook itself must remain, even as empty function, as otherwise there will be linker errors. That would reduce the file to the following:

```cpp
isEmpty(QT_JSONSERIALIZER_REGPATH): QT_JSONSERIALIZER_REGPATH = $$OUT_PWD/.reggen
mkpath($$QT_JSONSERIALIZER_REGPATH)

startup_hookfile = "void qtJsonSerializerRegisterTypes() {}"
out_file = $$QT_JSONSERIALIZER_REGPATH/qjsonconverterreg_all.cpp
!exists($$out_file):!write_file($$out_file, startup_hookfile):error("Failed to create $$out_file")
GENERATED_SOURCES += $$out_file
```

**Comment by useful-friend** [comment]
Thanks for the code.
It drastically reduced the binary size but I see that all the de/serialize processes in my code are working well even with nothing being registered and I don't know why.
Another thing that crossed my mind was removing type converters that I don't need in [typeconverters.pri](https://github.com/Skycoder42/QtJsonSerializer/blob/3.3.1-3/src/jsonserializer/typeconverters/typeconverters.pri).
I wanted to know what are those files and ask if it is ok to remove them?
I would appreciate it if you describe the mechanism of type converters and their registrations.

**Comment by Skycoder42** [comment]
The library basically has two kinds of conversion (which, unfortunately, are all named "typeconverters" due to a shortsight of mine)
1. Container converters
2. Serializers

## Container converters
The first group is what is generated with the `typesplit.pri` file and is responsible for generalizing generic types, e.g.:
```
QList<int> <=> QVariantList
QMap<QString, double> <=> QVariantMap
....
```
This allows the library to de/serialize any generic type, as long as such a converter has been registered for that type. You can register those manually via `QJsonSerializer::register*` methods. Please note that this part has drastically changed with the 4.0.0 release and is no longer valid, but for your version, that's the task these methods (and the startup hook) have.

Removing the hook simply means, that you cannot convert generic containers anymore. If you have for example a `QList<int>` somewhere, it will stop working, unless you manually call `QJsonSerializer::registerListConverters<int>` in your code. The hook is simply provided to automatically do these registrations for common Qt types so you don't have to.

## Serializers
The `QJsonTypeConverter` classes in contrast are responsible for doing the actual conversion between C++ and JSON. Some basic types are converted implicitly, but most types, (e.g. lists, objects, ...) need a converter. This split between the core serializer and the converters makes the library flexible and easy to extend.

Some of these converters require a certain "Container converter" to be registered for work. For example, the `QJsonListConverter` can de/serialize any `QList<T>`, as long as `T` was registered via `QJsonSerializer::registerListConverters<T>`. It can also work with `QVariantList`, so if you want to avoid the conversion all together, use `QVariantList` properties and you are good.

You can simply remove any converter from `typeconverters.pri` you don't need, e.g. if you do not use `QVersionNumber`, you can remove the `QJsonVersionNumberConverter`. Remove the header and source file from `typeconverters.pri` and remove the [include](https://github.com/Skycoder42/QtJsonSerializer/blob/3.3.1-3/src/jsonserializer/qjsonserializer.cpp#L11) and [registration](https://github.com/Skycoder42/QtJsonSerializer/blob/3.3.1-3/src/jsonserializer/qjsonserializer.cpp#L490) from the `qjsonserializer.cpp` file.

**Comment by useful-friend** [comment]
Thanks for the complete clarification and your time.
