### ISSUE TITLE
Question On Usage of the library.

### ISSUE THREAD

**Issue by p0int3r** [Skycoder42/QJsonSerializer#25]
I would like to serialise `QList<TestObject *> *`  and `QHash<QString,TestObject *> *`  and i am having a bit of a hard time figuring out how to do it. More specifically i am trying to serialise lists and hashes that are members of a class but have been allocated on the heap instead of the stack. I would appreciate your help. 

Awesome library by the way!!!

**Comment by Skycoder42** [comment]
This is not possible out of the box, as dynamic allocation is generally not supported by the library. The only exceptions are `QObject*` and gadgets.

The reason is, that for dynamic allocation, there is no support in `QVariant` - which would be required for this. Gadgets and Objects have their own custom way of creating pointer instances.

I would recommend you to instead create `helper properties` that take values instead of pointers:
```
class MyClass
{
    Q_PROPERTY(QList<TestObject*>* objListPtr MEMBER _objListPtr NOTIFY objListPtrChanged STORED false)
    Q_PROPERTY(QList<TestObject*> objList READ getObjList WRITE setObjList NOTIFY objListChanged)

private:
    QList<TestObject*> *_objListPtr;

    QList<TestObject*> getObjList() const {
        return _objListPtr ? *_objListPtr : QList<TestObject*>{};
    }

    void setObjList(QList<TestObject*> value) {
        if (_objListPtr)
            delete _objListPtr;
        _objListPtr = new QList<TestObject*>{std::move(value)};
        emit objListChanged(*_objListPtr);
        emit objListPtrChanged(_objListPtr);
    }
};
```

This works as expected, unless you want to handle the `nullptr` case correctly (i.e. have a `null` JSON/CBOR value if `_objListPtr == nullptr`). In that case you would have to implement a custom type converter instead. See [QtJsonSerializer::TypeConverter](https://skycoder42.github.io/QtJsonSerializer/class_qt_json_serializer_1_1_type_converter.html#details) for how to create one.

**Comment by p0int3r** [comment]
That will work. Thank you!
