### ISSUE TITLE
(De-)serializing QObject tree

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#4]
How can QObject derived object with child objects be used with QtJsonSerializer? I mean that QObject already has children() getter. Is it possible to reuse embedded child-parent methods in collaboration with Q_PROPERTY instead of explicit adding m_children field?

**Comment by Skycoder42** [comment]
Yes it is. A property can also be defined with explicit getters and setters. For your case that would be:

```
Q_PROPERTY(QList<QObject*> children READ children WRITE setChildren)
```

You will have to implement the `setChildren` yourself:

```
void setChildren(const QList<QObject*> &children) {
    for(auto child : children)
        child->setParent(this);
}
```

Please note that in order for this to work, all of the children your serialized object has must be polymorphic! Otherwise the childrens properties won't be serialized. See [QJsonSerializer::polymorphing](https://skycoder42.github.io/QtJsonSerializer/class_q_json_serializer.html#ab3bf93ba232658e79a2a007d1f3d5239) for more details.

**Comment by Skycoder42** [comment]
Was I able to answer your question? If yes please close the issue

**Comment by arietto** [comment]
Yes, thank you.
