### ISSUE TITLE
Runtime termination when serializing QList<std::complex<double>>

### ISSUE THREAD

**Issue by wartista** [Skycoder42/QJsonSerializer#9]
I have a class definition as followed (In shortly):
```
class Model : public QObject
{
    Q_OBJECT
    Q_PROPERTY(QList<std::complex<double>> Chi MEMBER Chi)

protected:

    QList <std::complex<double>> Chi;
}
```
And I declared the metatype as you stated:
`Q_DECLARE_METATYPE(std::complex<double>)
`
In usage, I register the list as you suggested;
`QJsonSerializer::registerListConverters<std::complex<double>>();`

And when It comes to serilaze it throws exception and terminates:

```
terminate called after throwing an instance of 'QJsonSerializationException'
  what():  what: Failed to serialize with error: Failed to convert type std::complex<double> to a JSON representation
Property Trace:
        Chi (Type: QList<std::complex<double> >)
        [0] (Type: std::complex<double>)

This application has requested the Runtime to terminate it in an unusual way.
```
I know it is a matter of conversion thing and It would be lifesaver resolving this.

Regards

**Comment by Skycoder42** [comment]
The problem here is that the QVariant conversion from `std::complex<double>`, wrappend inside a `QVariant` to `QJsonValue` fails - In other words, the problem is the type itself, not the list. And that is not really an error, but expected behaviour - without you specifing a way to convert the (to the serializer) opaque type to a type that can be written as json, how should the serializer be able to.

To resolve the problem, you simply need to make the type convertible. There are basically two ways to do this.
1. Register a QVariant-Converter from `std::complex<double>` to `QString` and back (See [QMetaType::registerConverter](https://doc.qt.io/qt-5/qmetatype.html#registerConverter)). This is the easiest way, but not as beautiful, as your numeric value will be represented as string.
2. Implement and register a custom [QJsonTypeConverter](https://skycoder42.github.io/QtJsonSerializer/class_q_json_type_converter.html#details) that generates json out of the complex type. The page linked above has an example on how to do so.

**Edit:** If you end up going for the second way, feel free to contribute the resulting converter so it can be made available for anyone

**Comment by wartista** [comment]
Thank you very much for your fast return. If I implement the second way I'll imform you
